name: Scrape NSAA -> Build JSON
on:
  schedule:
    - cron: '15 11 * * *'   # runs daily ~06:15 America/Chicago (GitHub uses UTC)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python scraper/scrape_nsaa.py
          test -f site/data/football.json

      - name: Commit & push if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add site/data/football.json
            git commit -m "chore: update football.json ($(date -u +'%Y-%m-%d %H:%M:%SZ'))"
            git push
          else
            echo "No changes to commit."
          fi
